export const LEGAL_CONFIG = {
  brandName: "NLOCK",
  legalLastUpdated: "25 de agosto de 2026",
  companyName: "VERTEX LABS, UNIPESSOAL LDA",
  websiteUrl: "https://www.nlock.pt",
  supportEmail: "nlock@nlock.pt",
  privacyEmail: "nlock@nlock.pt",
  legalEmail: "nlock@nlock.pt",
  controllerName: "VERTEX LABS, UNIPESSOAL LDA",
  controllerAddress: "Estrada N3, Torre do Bispo, S. Vicente do Paul, 2000-687 Santarém, Portugal",
  controllerVat: "519599195",
  complaintsBookUrl: "https://www.livroreclamacoes.pt/Inicio/",
  adrName: "CNIACC — Centro Nacional de Informação e Arbitragem de Conflitos de Consumo",
  adrUrl: "https://www.cniacc.pt/pt/",
  adrEmail: "geral@cniacc.pt",
  adrPhone: "253 619 107",
  adrListUrl: "https://www.consumidor.gov.pt/consumidor_4/direitos-dos-consumidores1/conflitos-de-consumo",
  retentionNote:
    "Alguns dados podem ser conservados por prazo superior quando tal seja necessário para cumprir obrigações legais, exercer direitos ou responder a litígios.",
  dataRetention: {
    accountDeletion: "até 30 dias após o pedido de eliminação ou encerramento da conta",
    backups: "eliminação progressiva até 90 dias",
    billing: "10 anos civis subsequentes, nos termos fiscais aplicáveis",
    leads: "12 meses após o último contacto, quando não exista conversão",
    incompleteApplications: "6 meses após a última interação",
    consentRecords: "durante o período necessário para demonstrar o consentimento e cumprir obrigações legais",
  },
  cookieRetention: {
    consent: "até ser apagada pelo utilizador ou substituída por nova preferência",
    language: "até ser apagada pelo utilizador",
    publicPoll: "12 meses",
    session: "durante a sessão ou enquanto o utilizador optar por manter a sessão iniciada",
  },
};
