"use client";

import Link from "next/link";
import { ArrowRight, Award, Clock3, Crown, Gift, Lightbulb, Menu, MessageSquareText, ShieldCheck, Sparkles, TrendingUp, Users, X } from "lucide-react";
import { createElement, useState } from "react";
import ThemeToggle from "../../src/components/ThemeToggle";

function Brand() {
  return <span className="inline-flex items-center gap-2.5" aria-label="NLOCK"><span aria-hidden="true" className="nlock-placeholder-mark h-8 w-8">N</span><span className="nlock-wordmark text-sm text-white sm:text-base">NLOCK</span></span>;
}

const advantages = [
  { icon: Crown, title: "Identidade histórica", text: "Badge exclusivo e um número único entre Fundador #1 e Fundador #50. O teu lugar na história da NLOCK nunca é reatribuído." },
  { icon: Gift, title: "Preço de Lançamento", text: "199,90 € por ano — equivalente a 16,66 € por mês — enquanto mantiveres a subscrição de Fundador elegível ativa." },
  { icon: Lightbulb, title: "Influência no produto", text: "Ajuda a validar ideias, fluxos e funcionalidades através de perguntas e tarefas estruturadas dentro da NLOCK." },
  { icon: Award, title: "Reconhecimento visível", text: "Presença no Mural de Fundadores e destaques pelo contributo para o ecossistema NLOCK." },
  { icon: Users, title: "Crescimento partilhado", text: "Por cada três referrals convertidos, recebes 30 dias de NLOCK, até ao máximo de seis meses por ano." },
  { icon: MessageSquareText, title: "Proximidade à equipa", text: "Prioridade em oportunidades de validação e uma ligação mais direta à evolução de uma ferramenta feita para coaches." },
];

export default function AffiliateProgrammePage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <div className="nlock-test nlock-founder-page min-h-screen bg-[#05090f] text-white">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#05090f]/80 backdrop-blur-xl">
        <div className="mx-auto flex h-[72px] max-w-[var(--content-max)] items-center justify-between px-[var(--page-gutter)]">
          <Link href="/"><Brand /></Link>
          <nav className="hidden items-center gap-8 text-sm text-white/60 lg:flex"><a href="#advantages" className="transition hover:text-white">Vantagens</a><a href="#influence" className="transition hover:text-white">Influência</a><a href="#conditions" className="transition hover:text-white">Condições</a></nav>
          <div className="flex items-center gap-2"><ThemeToggle language="pt" className="!border-white/10 !bg-white/5 !text-white" /><Link href="/signup?mode=subscription&founder=1" className="hidden min-h-11 items-center rounded-[var(--radius-md)] bg-[image:var(--brand-gradient)] px-5 text-sm font-semibold text-[#03130e] sm:inline-flex">Ativar plano anual</Link><button type="button" onClick={() => setMenuOpen((value) => !value)} className="flex h-11 w-11 items-center justify-center rounded-[var(--radius-md)] border border-white/10 lg:hidden" aria-label="Abrir navegação">{menuOpen ? <X size={18} /> : <Menu size={18} />}</button></div>
        </div>
        {menuOpen ? <nav className="grid gap-2 border-t border-white/10 bg-[#05090f] p-4 lg:hidden">{[["#advantages", "Vantagens"], ["#influence", "Influência"], ["#conditions", "Condições"]].map(([href, label]) => <a key={href} href={href} onClick={() => setMenuOpen(false)} className="rounded-xl px-4 py-3 text-white/70">{label}</a>)}<Link href="/signup?mode=subscription&founder=1" className="rounded-xl bg-[image:var(--brand-gradient)] px-4 py-3 text-center font-semibold text-[#03130e]">Ativar plano anual</Link></nav> : null}
      </header>

      <main>
        <section className="nlock-founder-hero relative overflow-hidden px-[var(--page-gutter)] pb-24 pt-40 sm:pb-32 sm:pt-48">
          <div className="absolute left-[12%] top-24 h-[460px] w-[460px] rounded-full bg-[var(--brand-mint)]/12 blur-[130px]" /><div className="absolute right-[8%] top-40 h-[400px] w-[400px] rounded-full bg-[var(--brand-sky)]/10 blur-[140px]" />
          <div className="relative mx-auto grid max-w-[var(--content-max)] gap-12 lg:grid-cols-[1fr_0.52fr] lg:items-center">
            <div><span className="inline-flex rounded-full bg-[var(--brand-mint)] px-4 py-2 text-xs font-bold tracking-[0.18em] text-[#03130e]">APENAS 50 COACHES FUNDADORES</span><h1 className="mt-8 max-w-5xl text-[clamp(3.4rem,7.5vw,7.2rem)] font-semibold leading-[0.88] tracking-[-0.065em]">DESBLOQUEIA O TEU<br /><span className="bg-[image:var(--brand-gradient)] bg-clip-text text-transparent">POTENCIAL COMPLETO.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/60 sm:text-xl">Os primeiros 50 coaches que ativarem o plano anual tornam-se Fundadores automaticamente — com identidade histórica, Preço de Lançamento e participação mais próxima na evolução da NLOCK.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/signup?mode=subscription&founder=1" className="inline-flex min-h-[54px] items-center justify-center gap-2 rounded-[var(--radius-md)] bg-[image:var(--brand-gradient)] px-7 font-semibold text-[#03130e] shadow-[var(--shadow-accent)]">Ativar plano anual <ArrowRight size={18} /></Link><a href="#advantages" className="inline-flex min-h-[54px] items-center justify-center rounded-[var(--radius-md)] border border-white/15 bg-white/5 px-7 font-semibold">Ver vantagens</a></div></div>
            <aside className="nlock-founder-badge rounded-[30px] border border-[var(--brand-mint)]/30 bg-[linear-gradient(145deg,rgba(57,185,138,0.16),rgba(12,19,29,0.94))] p-8 shadow-[var(--shadow-accent)] sm:p-10"><Crown size={32} className="text-[var(--brand-mint)]" /><p className="mt-12 text-xs font-semibold tracking-[0.22em] text-[var(--brand-mint)]">FUNDADOR</p><p className="mt-2 text-7xl font-semibold tracking-[-0.07em]">#17</p><div className="mt-9 border-t border-white/10 pt-6"><p className="text-sm text-white/45">Preço de Lançamento</p><p className="mt-2 text-3xl font-semibold">199,90 € <span className="text-base font-normal text-white/40">/ano</span></p><p className="mt-2 text-sm text-white/40">≈ 16,66 €/mês</p></div></aside>
          </div>
        </section>

        <section id="advantages" className="border-y border-white/10 bg-[#080d14] px-[var(--page-gutter)] py-[var(--section-space)]"><div className="mx-auto max-w-[var(--content-max)]"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[var(--brand-mint)]">Vantagens de ser Fundador</p><h2 className="mt-5 max-w-4xl text-[clamp(2.7rem,6vw,5.5rem)] font-semibold leading-[0.95] tracking-[-0.055em]">Entra no primeiro capítulo.<br /><span className="text-white/38">Leva mais da NLOCK contigo.</span></h2><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{advantages.map(({ icon, title, text }) => <article key={title} className="nlock-founder-feature rounded-[24px] border border-white/10 bg-[#0c131d] p-7">{createElement(icon, { size: 24, className: "text-[var(--brand-mint)]" })}<h3 className="mt-9 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-white/50">{text}</p></article>)}</div></div></section>

        <section id="influence" className="px-[var(--page-gutter)] py-[var(--section-space)]"><div className="mx-auto grid max-w-[var(--content-max)] gap-10 lg:grid-cols-[0.86fr_1.14fr] lg:items-center"><div><Sparkles size={32} className="text-[var(--brand-mint)]" /><h2 className="mt-7 text-[clamp(2.7rem,5vw,5rem)] font-semibold leading-[0.95] tracking-[-0.055em]">Ajuda a moldar a NLOCK.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/55">Recebe perguntas estruturadas, valida decisões em contexto real e partilha feedback enquanto o produto evolui. Os Fundadores influenciam a direção — a decisão final permanece com a NLOCK.</p></div><article className="nlock-founder-input rounded-[28px] border border-[var(--brand-mint)]/25 bg-[linear-gradient(145deg,rgba(57,185,138,0.12),rgba(12,19,29,1))] p-7 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--brand-mint)]">NLOCK INPUT · EXEMPLO</p><p className="mt-7 text-2xl font-semibold leading-9">“Estamos a validar a próxima evolução da preparação de sessões.”</p><div className="mt-9 flex flex-wrap items-center justify-between gap-3"><span className="text-sm text-white/45"><Clock3 size={16} className="mr-2 inline" />Disponível durante 48h</span><span className="rounded-full bg-[var(--brand-mint)] px-4 py-2 text-sm font-semibold text-[#03130e]">Contributo reconhecido</span></div></article></div></section>

        <section className="border-y border-white/10 bg-[#080d14] px-[var(--page-gutter)] py-[var(--section-space)]"><div className="mx-auto max-w-[var(--content-max)]"><div className="grid gap-5 lg:grid-cols-3"><article className="nlock-founder-feature rounded-[26px] border border-white/10 bg-[#0c131d] p-7"><Gift className="text-[var(--brand-mint)]" /><p className="mt-12 text-xs font-semibold uppercase tracking-[0.18em] text-white/35">Referrals convertidos</p><h3 className="mt-3 text-3xl font-semibold">3 referrals<br /><span className="text-[var(--brand-mint)]">+30 dias</span></h3><p className="mt-5 leading-7 text-white/50">Máximo de seis meses de subscrição por ano.</p></article><article className="nlock-founder-feature rounded-[26px] border border-white/10 bg-[#0c131d] p-7"><TrendingUp className="text-[var(--brand-mint)]" /><p className="mt-12 text-xs font-semibold uppercase tracking-[0.18em] text-white/35">Participação ativa</p><h3 className="mt-3 text-3xl font-semibold">Mais contributo.<br /><span className="text-[var(--brand-mint)]">Mais vantagens.</span></h3><p className="mt-5 leading-7 text-white/50">Quanto mais ajudas a NLOCK, mais reconhecimento e oportunidades podes receber dentro do programa.</p></article><article className="nlock-founder-feature rounded-[26px] border border-white/10 bg-[#0c131d] p-7"><Award className="text-[var(--brand-mint)]" /><p className="mt-12 text-xs font-semibold uppercase tracking-[0.18em] text-white/35">Mural de Fundadores</p><h3 className="mt-3 text-3xl font-semibold">Perfil, badge<br /><span className="text-white/35">e visibilidade</span></h3><p className="mt-5 leading-7 text-white/50">Reconhecimento público para Fundadores ativos, apresentados por ordem histórica.</p></article></div></div></section>

        <section id="conditions" className="px-[var(--page-gutter)] py-[var(--section-space)]"><div className="mx-auto grid max-w-[var(--content-max)] gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div><ShieldCheck size={34} className="text-[var(--brand-mint)]" /><h2 className="mt-7 text-4xl font-semibold tracking-[-0.045em]">Um estatuto exclusivo, com condições claras.</h2></div><div className="grid gap-5 sm:grid-cols-2">{[["Atribuição automática", "Os primeiros 50 coaches que ativarem uma subscrição anual elegível recebem automaticamente o estatuto."], ["Número histórico", "Se cancelares, o número permanece teu e nunca será atribuído a outro coach."], ["Benefícios ativos", "Cancelar remove o badge ativo, Preço de Lançamento, recompensas, ranking e visibilidade no mural."], ["Reconhecimento, não certificação", "O estatuto de Fundador reconhece participação na NLOCK; não certifica nem recomenda serviços profissionais."]].map(([title, text]) => <article key={title} className="border-t border-white/15 pt-5"><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/45">{text}</p></article>)}</div></div></section>

        <section className="nlock-founder-cta px-[var(--page-gutter)] pb-[var(--section-space)] text-center"><div className="mx-auto max-w-5xl rounded-[32px] border border-[var(--brand-mint)]/25 bg-[linear-gradient(135deg,rgba(57,185,138,0.16),rgba(67,144,211,0.09),rgba(12,19,29,1))] px-6 py-16 sm:px-12 sm:py-20"><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[var(--brand-mint)]">As primeiras 50 vagas</p><h2 className="mt-6 text-[clamp(3rem,7vw,6.2rem)] font-semibold leading-[0.9] tracking-[-0.06em]">DESBLOQUEIA O TEU<br /><span className="bg-[image:var(--brand-gradient)] bg-clip-text text-transparent">POTENCIAL COMPLETO.</span></h2><Link href="/signup?mode=subscription&founder=1" className="mt-10 inline-flex min-h-[54px] items-center justify-center gap-2 rounded-[var(--radius-md)] bg-[image:var(--brand-gradient)] px-7 font-semibold text-[#03130e]">Começar como Fundador <ArrowRight size={18} /></Link></div></section>
      </main>
      <footer className="border-t border-white/10 px-[var(--page-gutter)] py-8"><div className="mx-auto flex max-w-[var(--content-max)] flex-col items-center justify-between gap-5 text-sm text-white/40 sm:flex-row"><Link href="/"><Brand /></Link><p>Limitado aos primeiros 50 Coaches Fundadores elegíveis.</p></div></footer>
    </div>
  );
}
